version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
